### ISSUE TITLE
当Fricsion调整的值越大，关闭侧滑页时，MainActivity页总是先显示一个空白页

### ISSUE THREAD

**Issue by build-hanwei** [peng8350/JPSpringMenu#1]
当Fricsion只要调整过，调整的值越大，关闭侧滑页时，主界面恢复显示的时候总是先显示一个空白页面，再重新显示主界面。如果不动Fricsion，则基本看不出来这个空白页
![image](https://user-images.githubusercontent.com/31239359/30894813-9a2f9690-a378-11e7-919d-0bb9e151c46f.png)

![s70927-111803](https://user-images.githubusercontent.com/31239359/30894803-7b4de164-a378-11e7-84d0-34dd7f580f28.jpg)

**Comment by peng8350** [comment]
好吧,是我变量进度x引用放错位置造成的,谢谢反馈

**Comment by build-hanwei** [comment]
楼主，下载源码包没问题了，但是添加依赖还是不行的，我添加依赖的包是“compile 'com.jpeng:jpspringmenu:1.0.2'”

**Comment by peng8350** [comment]
@build-hanwei   
`repositories {`
`        jcenter()`
`    }`
