### ISSUE TITLE
出现一些bug

### ISSUE THREAD

**Issue by ZhaoLoveGao** [peng8350/JPSpringMenu#2]
第一个问题，当第一次打开页面时，向左进行侧滑时（不用按钮，用手势滑动），侧滑不了。第二个，当你侧滑了一边并关掉，进行另一边的时候（不用按钮，用手势滑动）侧滑不了

**Comment by peng8350** [comment]
1.这个问题是因为我默认选择只能从左边滑出，所以你想打开右边，也就是向左滑是不行的
2.设计上，要不就只能左边滑出要不就右边，所以你选择了左边方向后，右边是不能滑的

**Comment by ZhaoLoveGao** [comment]
嗯嗯，没有问题来了啊。我刚才没有看到设置方向的方法，误解了啊，做的挺帅的，大佬。

**Comment by peng8350** [comment]
问题应该还有的，不过thanks for   your encouragement
